name: Update and Deploy ICS Calendars

on:
  schedule:
    - cron: '0 */6 * * *'  # alle 6 Stunden
  workflow_dispatch: # manuelles Ausl√∂sen erlaubt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Node.js Setup
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Update ICS Calendars
      env:
        TEAM_ID: "167881"  # besser als Secret speichern
      run: npm run update

    - name: Deploy ICS to gh-pages
      run: |
        git config --global user.email "bbb-api@oliver-eder.de"
        git config --global user.name "GitHub Actions"
        git checkout --orphan gh-pages
        git rm -rf .
        cp -r public/ics/* .
        git add .
        git commit -m "Deploy ICS Kalender $(date +'%Y-%m-%d %H:%M:%S')"
        git push -f origin gh-pages
