name: Update ICS Calendars

on:
  schedule:
    - cron: '0 */6 * * *' # Alle 6 Stunden
  workflow_dispatch: # manueller Start

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node.js installieren
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Kalender aktualisieren
        env:
          TEAM_ID: "<DEIN_TEAM_ID>"
        run: npm run update

      - name: ICS Dateien zum GitHub Repo hinzufügen
        run: |
          git config --global user.email "bbb-api@oliver-eder.de"
          git config --global user.name "github-actions"
          git add public/ics/*.ics
          git commit -m "Update ICS Kalender-Dateien"
          git push